### ISSUE TITLE
RTD version of develguide is not updated

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/develguide#17]
Looks like the read-the-docs (RTD) version of the develguide did not update for the last two years. Looking over the RTD project it seems like the branch used to build the *latest* version was *develop* rather than *master*.
Creating a *develop* branch in this repo doesn't seem to trigger a build on RTD, maybe the webhook is broken as well.

@aradi has access to the RTD project and can trigger a build for sure.

**Comment by aradi** [comment]
It works now, thanks! :wink:
